### ISSUE TITLE
Fishing Breaks

### ISSUE THREAD

**Issue by WaffleManTheGreat** [primetime43/Toontown-Rewritten-Bot#14]
Ive installed all of the .NET frameworks but whenever you press start fishing the application crashes.

Ive found a temporary fix though. You seem to have to clone the repository into visual studio and then run it from there for it to work.

**Comment by primetime43** [comment]
> Ive installed all of the .NET frameworks but whenever you press start fishing the application crashes.
> 
> Ive found a temporary fix though. You seem to have to clone the repository into visual studio and then run it from there for it to work.

hmm that doesn't make much sense. Does it only crash trying to fish or other things too? It may be cause its missing a dll but I dont think so because I packed it into the exe.

**Comment by WaffleManTheGreat** [comment]
i will check real quick

**Comment by WaffleManTheGreat** [comment]
I tried the chat feature and the golfing feature, both of which seem to not work! I tried resetting the Coordinates from the dev tab but that crashes the application and gives this error:  
![image](https://user-images.githubusercontent.com/113483280/223615662-7abd0aac-b411-4342-8ca3-4c93c52c1bc3.png)
here is the complete log:

[log372023.txt](https://github.com/primetime43/Toontown-Rewritten-Bot/files/10917062/log372023.txt)

**Comment by primetime43** [comment]
FIxed in 1.4.1
