### ISSUE TITLE
Toontown Rewritten is not running

### ISSUE THREAD

**Issue by ImAnjoo** [primetime43/Toontown-Rewritten-Bot#17]
When I try to run the ToonTown Rewritten Bot.exe file, the following error pops up:

"ToonTown Rewritten is not running!"

Even though I have the game open, this error is popping up and I'm not sure why.

**Comment by primetime43** [comment]
If you have the latest version, you shouldn't be seeing that pop-up. I believe I removed it a few versions back. https://github.com/primetime43/Toontown-Rewritten-Bot/releases/tag/1.4.1

**Comment by ImAnjoo** [comment]
Apologies, I had the older version installed
