### ISSUE TITLE
problem opening program.

### ISSUE THREAD

**Issue by starchild333** [primetime43/Toontown-Rewritten-Bot#19]
how do we open the program? there is no exe or program file.

**Comment by starchild333** [comment]
i downloaded the file and opened it with winrar but there is no .exe file for me to launch. am i doing something wrong?

**Comment by primetime43** [comment]
![image](https://github.com/primetime43/Toontown-Rewritten-Bot/assets/12754111/2bca1e03-bbea-4f75-b948-d23ac9b91ee6)
Its in there
