### ISSUE TITLE
Golfing

### ISSUE THREAD

**Issue by Trancebeep** [primetime43/Toontown-Rewritten-Bot#21]
Hello, the golf bot does not work, i load into a course, click on the correct option in the bot and it does nothing at all, sometimes it even freezes and awaits response from program

**Comment by JJBrasch** [comment]
@Trancebeep I'm experiencing the same issues, @primetime43 is there any solution here?

**Comment by primetime43** [comment]
> @Trancebeep I'm experiencing the same issues, @primetime43 is there any solution here?

It seems the game has been updated a lot since I've last worked on the bot. I'll see if I can look into getting it fixed this weekend.

**Comment by JJBrasch** [comment]
Thanks @primetime43!

**Comment by JJBrasch** [comment]
Any update on this @primetime43?

**Comment by primetime43** [comment]
> Any update on this @primetime43?

I've been working on it for about two weeks now. So I should have a new release soon hopefully.

**Comment by primetime43** [comment]
07fe46ed04e405f62e84d2d2f6d15e8a44ed5773 should fix this

**Comment by primetime43** [comment]
Completed in version 1.5.0

**Comment by JJBrasch** [comment]
@primetime43 hey man, I might be stupid but I don't see the exe file in the new 1.5 version. Any thoughts?

**Comment by primetime43** [comment]
> @primetime43 hey man, I might be stupid but I don't see the exe file in the new 1.5 version. Any thoughts?

Its right here in the releases

![image](https://github.com/primetime43/Toontown-Rewritten-Bot/assets/12754111/1fcef6b4-2356-4239-8f05-4463e6a3b076)

https://github.com/primetime43/Toontown-Rewritten-Bot/releases/tag/1.5.0

**Comment by JJBrasch** [comment]
@primetime43 don't know how I missed that, thanks!
