### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by blakeyoung81** [primetime43/Toontown-Rewritten-Bot#3]
Hey there, the fishing bit doesn’t recognize a catch. The color code Id must not be working or maybe the color changed. 

Also, the algorithm needs to be optimized as it results in a net loss with the gold rod. Smart fishing doesn’t seem too hard. Just iterate through pixels to find dark, update coordinates, cast in the vector opposite the distance to spot and your good. Thanks

**Comment by primetime43** [comment]
Yea, I need to update it a lot, thanks for the heads up!

**Comment by primetime43** [comment]
Should be fixed in the update.
