### ISSUE TITLE
Doesn't work on my cp

### ISSUE THREAD

**Issue by blakeyoung81** [primetime43/Toontown-Rewritten-Bot#5]
Hey there, 
Unfortunately, it doesn't work on my computer anymore. I click start and the program just disappears. Any ideas?

**Comment by primetime43** [comment]
> Hey there, Unfortunately, it doesn't work on my computer anymore. I click start and the program just disappears. Any ideas?

No sure. I'll try to look into it over the next few weeks.

**Comment by primetime43** [comment]
@blakeyoung81 it should be fixed now. I was forgetting to add the resources in the rar and only provided the exe. My bad.
