### ISSUE TITLE
Unable to run new update

### ISSUE THREAD

**Issue by Cmarlowe132** [primetime43/Toontown-Rewritten-Bot#6]
With the newest update to the bot, I'm unsure how to download and run the newest release, since the last release I used the mediafire link from YouTube which came with the .exe and files all ready to go. Trying to move the .exe file into the same folder and replacing the old .exe seems to cause bugs.

**Comment by primetime43** [comment]
Okay, I'll look into it all again soon. Sorry for the issues.

**Comment by primetime43** [comment]
@Cmarlowe132 it should be fixed now. I was forgetting to add the resources in the rar and only provided the exe. My bad.
